-- MySQL Script generated by MySQL Workbench
-- Sun Jun 28 17:32:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tecVagas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tecVagas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tecVagas` DEFAULT CHARACTER SET utf8 ;
USE `tecVagas` ;

-- -----------------------------------------------------
-- Table `tecVagas`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecVagas`.`candidato` (
  `idCandidato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `sobrenome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `relacaoEtec` VARCHAR(10) NOT NULL,
  `curriculo` LONGBLOB NOT NULL,
  `deseja` VARCHAR(1) NULL,
  PRIMARY KEY (`idCandidato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecVagas`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecVagas`.`empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `cnpj` VARCHAR(18) NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `localizacao` VARCHAR(50) NOT NULL,
  `ramo` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `empresaParceira` VARCHAR(1) NOT NULL,
  `vagasAnunciadas` INT NOT NULL,
  `vagasAberto` INT NOT NULL,
  `logo` LONGBLOB NULL,
  `deseja` VARCHAR(1) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecVagas`.`vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecVagas`.`vaga` (
  `idVaga` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `preRequisitos` VARCHAR(500) NOT NULL,
  `tipoContrato` VARCHAR(30) NOT NULL,
  `jornada` VARCHAR(50) NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  `idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idVaga`),
  INDEX `fk_Vagas_Empresa1_idx` (`idEmpresa` ASC),
  CONSTRAINT `fk_Vagas_Empresa1`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `tecVagas`.`empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecVagas`.`candidatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecVagas`.`candidatar` (
  `idCandidatar` INT NOT NULL AUTO_INCREMENT,
  `idVaga` INT NOT NULL,
  `idCandidato` INT NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`idCandidatar`),
  INDEX `fk_Curriculo_has_Vagas_Vagas1_idx` (`idVaga` ASC),
  INDEX `fk_Curriculo_por_Vaga_Candidato1_idx` (`idCandidato` ASC),
  CONSTRAINT `fk_Curriculo_has_Vagas_Vagas1`
    FOREIGN KEY (`idVaga`)
    REFERENCES `tecVagas`.`vaga` (`idVaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curriculo_por_Vaga_Candidato1`
    FOREIGN KEY (`idCandidato`)
    REFERENCES `tecVagas`.`candidato` (`idCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecVagas`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecVagas`.`admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Criando o administrador padrão
-- -----------------------------------------------------
INSERT INTO admin (login, senha) VALUES ('admin', md5('admin'))